name: Import Server and Client Repos with History

on:
  workflow_dispatch: # Trigger manually for now

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # pull from server repo commits as well
      - name: Add server repo as remote and pull into server/
        run: |
          git remote add server-origin https://github.com/lkas96/PooPal-Server.git
          git fetch server-origin
          git subtree add --prefix=server server-origin main

      # pull from client repo commits as well
      - name: Add client repo as remote and pull into client/
        run: |
          git remote add client-origin https://github.com/lkas96/PooPal-Client.git
          git fetch client-origin
          git subtree add --prefix=client client-origin main

      - name: Push changes
        run: |
          git push origin main
